### ISSUE TITLE
a question about the code

### ISSUE THREAD

**Issue by csongyang** [squareRoot3/SLOTAlign#1]
Hello, Dear Tang, I am very interested in your work, but I have some problems when reading your code, can you help me to answer it？
When I read the paper, the optimization goal in the paper is shown in the figure below, but when I read your code, the optimization goal in the code is not consistent. How can I explain this?
![image](https://github.com/squareRoot3/SLOTAlign/assets/37408882/2edbe04d-a7e7-4584-890a-4c91c98734d8)
![image](https://github.com/squareRoot3/SLOTAlign/assets/37408882/ccc9e969-6a72-4941-a72e-f55c05a1340f)

**Comment by squareRoot3** [comment]
It seems that I foget 2*trace in the code?  I will check it later.

**Comment by csongyang** [comment]
Could you provide your WeChat so that we can communicate efficiently.

**Comment by csongyang** [comment]
WeChat :16601136958,   Songyang_Chen

**Comment by csongyang** [comment]
>
